version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Apache Maven"
      - yum-get update
      - yum-get install -y maven

  build:
    commands:
      - echo "Building the Java application"
      - mvn clean package

artifacts:
  files:
    - target/*.jar
